receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      load:
      memory:
      disk:
      filesystem:
      network:
      paging:
      processes:

exporters:
  file/rotation_with_custom_settings:
    path: /var/logs/otel
    rotation:
      max_megabytes: 10
      max_days: 3
      max_backups: 3
      localtime: true
    format: proto
    compression: zstd

processors:
  batch: {}

service:
  telemetry:
    metrics:
      address: 0.0.0.0:8889
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [batch]
      exporters: [file/rotation_with_custom_settings]
