apiVersion: v1alpha1
kind: Fleet
metadata:
  name: claw-machine-fleet
  labels:
    foo: bar
spec:
  selector:
    matchLabels:
      fleet: claw-machine-fleet
  template:
    spec:
      os:
        image: quay.io/mparrade/flightctl-agent-rhel@sha256:1ad312b05fcba1d19ca29133799e83bcf4e5e9ef2ebb1118e26fd642563c92e0
      config:
        - name: motd-update
          configType: InlineConfigProviderSpec
          inline:
            ignition:
              version: 3.4.0
            storage:
              files:
                - contents:
                    source: >-
                      data:,This%20system%20is%20managed%20by%20flightctl.%0A
                  mode: 422
                  overwrite: true
                  path: "/etc/motd"
        - name: microshift-manifests
          configType: GitConfigProviderSpec
          gitRef:  
            repository: claw-machine-manifests
            targetRevision: main
            path: /configuration
        - name: pull-secret
          configType: GitConfigProviderSpec
          gitRef:
            repository: mparra-pull-secret
            targetRevision: main
            path: /configuration
      systemd:
        matchPatterns:
          - "microshift.service"
          - "crio.service"
          - "flightctl-agent.service"
          - "otelcol-contrib.service"
