apiVersion: v1alpha1
kind: Fleet
metadata:
  name: claw-machine-fleet-v2
  labels:
    foo: bar
spec:
  selector:
    matchLabels:
      fleet: claw-machine-fleet-v2
  template:
    spec:
      os:
        image: quay.io/mparrade/flightctl-agent-extra-rhel:latest
      config:
        - name: motd-update
          configType: InlineConfigProviderSpec
          inline:
            ignition:
              version: 3.4.0
            storage:
              files:
                - contents:
                    source: >-
                      data:,This%20system%20is%20managed%20by%20flightctl.%0A
                  mode: 422
                  overwrite: true
                  path: "/etc/motd"
        - name: microshift-manifests
          configType: GitConfigProviderSpec
          gitRef:  
            repository: claw-machine-manifests
            targetRevision: main
            path: /configuration
        - name: config-from-k8s-secret
          configType: KubernetesSecretProviderSpec
          secretRef:
            name: mparra-pull-secret
            namespace: flightctl--runtime-ext
            mountPath: /etc/crio
      systemd:
        matchPatterns:
          - "microshift.service"
          - "crio.service"
          - "flightctl-agent.service"
          - "opentelemetry-collector-rhde.service"
