receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      load:
      memory:
      disk:
      filesystem:
      network:
      paging:
      processes:
      process:
        mute_process_name_error: true
        mute_process_exe_error: true
        mute_process_io_error: true
        metrics:
          process.cpu.utilization:
            enabled: true
          process.memory.utilization:
            enabled: true

exporters:
 otlphttp:
    endpoint: https://otel.flightctl.edge-devices.net:443
    tls:
      insecure: false
      insecure_skip_verify: true

processors:
  batch: {}
  attributes:
    actions:
      - action: insert
        key: device
        value: "fitlet2"

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [attributes,batch]
      exporters: [otlphttp]