kind: Deployment
apiVersion: apps/v1
metadata:
  name: edge-ws-connector
  namespace: edge-ws-connector
  labels:
    app: edge-ws-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-ws-connector
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: edge-ws-connector
    spec:
      volumes:
        - name: demo-claw-tls
          secret:
            secretName: demo-claw-tls
            items:
              - key: serverCA.crt
                path: serverCA.crt
              - key: client.key
                path: client.key
              - key: client.crt
                path: client.crt
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: edge-ws-connector
          env:        
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: edge-ws-connector
                  key: PORT
            - name: WS_MANAGER
              valueFrom:
                configMapKeyRef:
                  name: edge-ws-connector
                  key: WS_MANAGER
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8081
              protocol: TCP
          securityContext: {}
          imagePullPolicy: Always
          volumeMounts:
            - name: demo-claw-tls
              mountPath: /app/certs
          terminationMessagePolicy: File
          image: >-
            quay.io/mparrade/claw-edge-ws-connector:latest
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600